require 'rake'

desc 'Update and build all Vim plugin bundles'
task :default => 'bundles:distupdate'

namespace :bundles do
  task :cd do
    cd File.join(File.dirname(__FILE__), 'bundle')
  end

  desc 'Purge any unmanaged bundles from the bundle dir'
  task :clean do
    puts '== Cleaning unmanaged bundles...'
    system 'vim +BundleClean +q'
  end

  desc 'Install all Vim plugin bundles'
  task :install do
    puts '== Installing all Vundle-managed plugins...'
    system 'vim -c +BundleInstall +q'
  end

  desc 'Update specified bundles, or default to all'
  task :update, :bundle do |task, args|
    bundle = args[:bundle] || ''  # all
    puts '== Updating Vundle-managed plugins...'
    system "vim -c 'BundleInstall! #{bundle}' +BundleClean +q"
  end

  desc 'Post-install steps -- compilation, etc.'
  task :build => :cd do
    puts '== Building command-t plugin'
    cd('Command-T/ruby/command-t') do
      system '$HOME/.rvm/bin/rvm use system; ruby extconf.rb && make'
    end
  end

  desc 'Update and build all Vim plugin bundles'
  task :distupdate => [:update, :build]

end

