#!/usr/bin/env ruby

# Yanked with slight modification from Tammer Saleh's post:
#   http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen

git_bundles = [
  'git://github.com/mileszs/ack.vim.git',
  'git://github.com/msanders/snipmate.vim.git',
  'git://github.com/nelstrom/vim-blackboard.git',
  'git://github.com/scrooloose/nerdtree.git',
  'git://github.com/scrooloose/nerdcommenter.git',
  'git://github.com/timcharper/textile.vim.git',
  'git://github.com/tpope/vim-cucumber.git',
  'git://github.com/tpope/vim-endwise.git',
  'git://github.com/tpope/vim-git.git',
  'git://github.com/tpope/vim-markdown.git',
  'git://github.com/tpope/vim-rake.git',
  'git://github.com/tpope/vim-rails.git',
  'git://github.com/tpope/vim-repeat.git',
  'git://github.com/tpope/vim-surround.git',
  'git://github.com/tpope/vim-vividchalk.git',
  'git://github.com/wincent/Command-T.git',
  'git://github.com/vim-ruby/vim-ruby.git',
  'git://repo.or.cz/vcscommand'
  # "git://github.com/astashov/vim-ruby-debugger.git",
  # "git://github.com/tsaleh/vim-align.git",
  # "git://github.com/tsaleh/vim-supertab.git",
]

vim_org_scripts = [
  # ['IndexedSearch', '7062',  'plugin'],
  ['gist',          '13427',  'plugin'],
  ['tasklist',      '10388',  'plugin'],
  ['wordcomplete',  '6504',   'plugin'],
  ['jquery',        '12276',  'syntax'],
  ['matchit',       '8196',   'zip'],
  ['taglist',       '7701',   'zip'],
  ['yankring',      '13554',  'zip']
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), 'bundle')
FileUtils.cd(bundles_dir)

puts 'Trashing everything in .vim/bundle (lookout!)'
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone --depth 1 #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, '.git'))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.#{script_type == 'zip' ? 'zip' : 'vim'}")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, 'w') do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
  if script_type == 'zip'
    %x(unzip -d #{name} #{local_file} && rm -r #{name}/zip)
  end
end

# ==============================================================================
# = Post-install Steps
# ==============================================================================

puts '== Building command-t plugin'
FileUtils.cd('Command-T') do
  system '$HOME/.rvm/bin/rvm use system; rake make'
end

puts "== Nuking snipMate's built-in default snippets"
FileUtils.cd('snipmate.vim') do
  FileUtils.rm_rf 'snippets'
end

puts '== Removing extraneous vim-ruby repo stuff'
FileUtils.cd('vim-ruby') do
  FileUtils.rm_rf %w[ bin etc CONTRIBUTORS CHANGELOG FAQ NEWS INSTALL README Rakefile ]
end

puts "== Generating helptags with pathogen"
system 'vim -e -c "call pathogen#helptags()" -c q'
