addSbtPlugin("com.kalmanb.sbt" % "sbt-ctags" % "0.3.0")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")
addSbtPlugin("org.ensime" % "sbt-ensime" % "1.12.4")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.2.0")
addSbtPlugin("au.com.onegeek" %% "sbt-dotenv" % "1.1.36")
