// addSbtPlugin("com.kalmanb.sbt" % "sbt-ctags" % "0.3.0")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")
addSbtPlugin("org.ensime" % "sbt-ensime" % "2.1.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.3.3")
addSbtPlugin("au.com.onegeek" %% "sbt-dotenv" % "1.2.88")
addSbtPlugin("laughedelic" % "sbt-notifications" % "0.1.0")
