// addSbtPlugin("com.kalmanb.sbt" % "sbt-ctags" % "0.3.0")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.4.2")
addSbtPlugin("au.com.onegeek" %% "sbt-dotenv" % "2.0.117")
addSbtPlugin("laughedelic" % "sbt-notifications" % "0.1.0")
